@extends('layouts.admin')

@section('content')

@if(Route::is('header.*'))
    @if(Route::is('header.edit'))
        @include('section.admin.header-edit')
    @else
        @include('section.admin.header')
    @endif
@elseif(Route::is('banner.*'))
    @if(Route::is('banner.edit'))
        @include('section.admin.banner-edit')
    @else
        @include('section.admin.banner')
    @endif
@elseif(Route::is('product.*'))
    @if(Route::is('product.edit'))
        @include('section.admin.product-edit')
    @else
        @include('section.admin.product')
    @endif
@elseif(Route::is('featured.*'))
    @if(Route::is('featured.edit'))
        @include('section.admin.featured-edit')
    @else
        @include('section.admin.featured')
    @endif
@elseif(Route::is('sales.*'))
    @if(Route::is('sales.edit'))
        @include('section.admin.sales-edit')
    @else
        @include('section.admin.sales')
    @endif
@elseif(Route::is('footer.*'))
    @if(Route::is('footer.edit'))
        @include('section.admin.footer-edit')
    @else
        @include('section.admin.footer')
    @endif
@elseif(Route::is('contact.*'))
    @if(Route::is('contact.edit'))
        @include('section.admin.contact-widget-edit')
    @else
        @include('section.admin.contact-widget')
    @endif
@elseif(Route::is('marketplace.*'))
    @if(Route::is('marketplace.edit'))
        @include('section.admin.marketplace-edit')
    @else
        @include('section.admin.marketplace')
    @endif
@else
    <h1>Welcome Lads!</h1>
@endif

@endsection
